name: CD
on:
  push:
    branches: [master, production, docs]

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/miigon/blog/dispatches \
            -d '{"event_type":"deploy", "client_payload":{"branch": "${{ github.ref_name }}"}}'
